### ISSUE TITLE
Check process New Course Date Proposal Evaluation

### ISSUE THREAD

**Issue by karlosko** [pv207/jbpm-project#1]
skontrolovat ci dava zmysel to, ze modelujem aktivitu - "ciernu skrinku" kde ocakavam ze zareaguje niektory zo skolitelov, a za touto aktivitou rovno mam gateway vetviaci flow podla toho "ci request niektori zo Skolitelov potvrdil"

**Comment by jludvice** [comment]
presunuto do pv207/bpm-diagrams#4
