### ISSUE TITLE
Registration process - short survey 

### ISSUE THREAD

**Issue by karlosko** [pv207/jbpm-project#2]
Ako jeden z objectives som vybral upevnenie pozicie na trhu - respektive zvysenie podielu na trhu.
Dal som tam tri objectives - narast customerov ( xx% narast customerov), narast customerov zapisanych na kurz (xx% narast v pocte vyskolenych ludi) a ze urcitu cast nasich novych customerov budu tvorit byvali customeri konkurencie... 
cize by bolo asi nutne bud pri registracii alebo pri jeho prvom zapise na kurz, vnutit zakaznikovi aby mi nejako dal info o tom ci uz v minulosti vyuzival sluzby inej firmy alebo nie... 

ja by som to riesil tak, ze v procese zapisu kurzu, v momente ked uz bude vsetko na tej spravnej ceste k samotnemu zapisu uzivatela na kurz, tak este pred zapisom skontrolujem ze ci ide o prvy kurz uzivatela a ak ano tak mu podstrcim survey ze ci doteraz bol uz skoleny u inej firmy

poprosim vas o nazor

**Comment by jludvice** [comment]
presunuto do pv207/bpm-diagrams#3
